RFFF/1.0?CP-SPEC/1.0

CONFIG-0001   (    =  CONFIG-0001-A)          ; 00..FF =
CONFIG-0001-A (10: =  CONFIG-0001-B 50: = -)  ; 10..4F =
CONFIG-0001-B (20: =  / 40: = -)              ; 20..3F =

CONFIG-0002   (    =  CONFIG-0002-A)          ; 00..FF =
CONFIG-0002-A (10: == CONFIG-0002-B 50: = -)  ; 10..4F ==
CONFIG-0002-B (20: == / 40: = -)              ; 20..3F ==

CONFIG-0003   (    =  CONFIG-0003-A 40: = -)  ; 00..3F =
CONFIG-0003-A (10: =  CONFIG-0003-B 50: = -)  ; 10..4F =
CONFIG-0003-B (20: == / 40: = -)              ; 20..3F ==

CONFIG-0004   (    =  CONFIG-0004-A 30: = -)  ; 00..2F =
CONFIG-0004-A (10: == CONFIG-0004-B 50: = -)  ; 10..4F ==
CONFIG-0004-B (20: =  / 40: = -)              ; 20..3F =

CONFIG-0005   (    =  CONFIG-0005-A)          ; 00..FF =
CONFIG-0005-A (10: =  CONFIG-0005-B F0: = -)  ; 10..EF =
CONFIG-0005-B (04: =  CONFIG-0005-C B0: = -)  ; 04..AF =
CONFIG-0005-C (27: =  CONFIG-0005-D F0: = -)  ; 27..EF =
CONFIG-0005-D (10: =  / 40: = -)              ; 10..3F =

CONFIG-0006   (    =  CONFIG-0006-A)          ; 00..FF =
CONFIG-0006-A (10: =  CONFIG-0006-B F0: = -)  ; 10..EF =
CONFIG-0006-B (04: =  CONFIG-0006-C B0: = -)  ; 04..AF =
CONFIG-0006-C (27: =  CONFIG-0006-D F0: = -)  ; 27..EF =
CONFIG-0006-D (10: == / 40: = -)              ; 10..3F ==

CONFIG-0007   (    =  CONFIG-0007-A)          ; 00..FF =
CONFIG-0007-A (10: =  CONFIG-0007-B F0: = -)  ; 10..EF =
CONFIG-0007-B (04: =  CONFIG-0007-C B0: = -)  ; 04..AF =
CONFIG-0007-C (27: == CONFIG-0007-D F0: = -)  ; 27..EF ==
CONFIG-0007-D (10: =  / 40: = -)              ; 10..3F =

CONFIG-0008   (    =  CONFIG-0008-A)          ; 00..FF =
CONFIG-0008-A (10: =  CONFIG-0008-B F0: = -)  ; 10..EF =
CONFIG-0008-B (04: =  CONFIG-0008-C B0: = -)  ; 04..AF =
CONFIG-0008-C (27: == CONFIG-0008-D F0: = -)  ; 27..EF ==
CONFIG-0008-D (10: == / 40: = -)              ; 10..3F ==

CONFIG-0009   (    =  CONFIG-0009-A)          ; 00..FF =
CONFIG-0009-A (10: =  CONFIG-0009-B F0: = -)  ; 10..EF =
CONFIG-0009-B (04: == CONFIG-0009-C B0: = -)  ; 04..AF ==
CONFIG-0009-C (27: =  CONFIG-0009-D F0: = -)  ; 27..EF =
CONFIG-0009-D (10: =  / 40: = -)              ; 10..3F =

CONFIG-0010   (    =  CONFIG-0010-A)          ; 00..FF =
CONFIG-0010-A (10: =  CONFIG-0010-B F0: = -)  ; 10..EF =
CONFIG-0010-B (04: == CONFIG-0010-C B0: = -)  ; 04..AF ==
CONFIG-0010-C (27: =  CONFIG-0010-D F0: = -)  ; 27..EF =
CONFIG-0010-D (10: == / 40: = -)              ; 10..3F ==

CONFIG-0011   (    =  CONFIG-0011-A)          ; 00..FF =
CONFIG-0011-A (10: =  CONFIG-0011-B F0: = -)  ; 10..EF =
CONFIG-0011-B (04: == CONFIG-0011-C B0: = -)  ; 04..AF ==
CONFIG-0011-C (27: == CONFIG-0011-D F0: = -)  ; 27..EF ==
CONFIG-0011-D (10: =  / 40: = -)              ; 10..3F =

CONFIG-0012   (    =  CONFIG-0012-A)          ; 00..FF =
CONFIG-0012-A (10: =  CONFIG-0012-B F0: = -)  ; 10..EF =
CONFIG-0012-B (04: == CONFIG-0012-C B0: = -)  ; 04..AF ==
CONFIG-0012-C (27: == CONFIG-0012-D F0: = -)  ; 27..EF ==
CONFIG-0012-D (10: == / 40: = -)              ; 10..3F ==

CONFIG-0013   (    =  CONFIG-0013-A)          ; 00..FF =
CONFIG-0013-A (10: == CONFIG-0013-B F0: = -)  ; 10..EF ==
CONFIG-0013-B (04: =  CONFIG-0013-C B0: = -)  ; 04..AF =
CONFIG-0013-C (27: =  CONFIG-0013-D F0: = -)  ; 27..EF =
CONFIG-0013-D (10: =  / 40: = -)              ; 10..3F =

CONFIG-0014   (    =  CONFIG-0014-A)          ; 00..FF =
CONFIG-0014-A (10: == CONFIG-0014-B F0: = -)  ; 10..EF ==
CONFIG-0014-B (04: =  CONFIG-0014-C B0: = -)  ; 04..AF =
CONFIG-0014-C (27: =  CONFIG-0014-D F0: = -)  ; 27..EF =
CONFIG-0014-D (10: == / 40: = -)              ; 10..3F ==

CONFIG-0015   (    =  CONFIG-0015-A)          ; 00..FF =
CONFIG-0015-A (10: == CONFIG-0015-B F0: = -)  ; 10..EF ==
CONFIG-0015-B (04: =  CONFIG-0015-C B0: = -)  ; 04..AF =
CONFIG-0015-C (27: == CONFIG-0015-D F0: = -)  ; 27..EF ==
CONFIG-0015-D (10: =  / 40: = -)              ; 10..3F =

CONFIG-0016   (    =  CONFIG-0016-A)          ; 00..FF =
CONFIG-0016-A (10: == CONFIG-0016-B F0: = -)  ; 10..EF ==
CONFIG-0016-B (04: =  CONFIG-0016-C B0: = -)  ; 04..AF =
CONFIG-0016-C (27: == CONFIG-0016-D F0: = -)  ; 27..EF ==
CONFIG-0016-D (10: == / 40: = -)              ; 10..3F ==

CONFIG-0017   (    =  CONFIG-0017-A)          ; 00..FF =
CONFIG-0017-A (10: == CONFIG-0017-B F0: = -)  ; 10..EF ==
CONFIG-0017-B (04: == CONFIG-0017-C B0: = -)  ; 04..AF ==
CONFIG-0017-C (27: =  CONFIG-0017-D F0: = -)  ; 27..EF =
CONFIG-0017-D (10: =  / 40: = -)              ; 10..3F =

CONFIG-0018   (    =  CONFIG-0018-A)          ; 00..FF =
CONFIG-0018-A (10: == CONFIG-0018-B F0: = -)  ; 10..EF ==
CONFIG-0018-B (04: == CONFIG-0018-C B0: = -)  ; 04..AF ==
CONFIG-0018-C (27: =  CONFIG-0018-D F0: = -)  ; 27..EF =
CONFIG-0018-D (10: == / 40: = -)              ; 10..3F ==

CONFIG-0019   (    =  CONFIG-0019-A)          ; 00..FF =
CONFIG-0019-A (10: == CONFIG-0019-B F0: = -)  ; 10..EF ==
CONFIG-0019-B (04: == CONFIG-0019-C B0: = -)  ; 04..AF ==
CONFIG-0019-C (27: == CONFIG-0019-D F0: = -)  ; 27..EF ==
CONFIG-0019-D (10: =  / 40: = -)              ; 10..3F =

CONFIG-0020   (    =  CONFIG-0020-A)          ; 00..FF =
CONFIG-0020-A (10: == CONFIG-0020-B F0: = -)  ; 10..EF ==
CONFIG-0020-B (04: == CONFIG-0020-C B0: = -)  ; 04..AF ==
CONFIG-0020-C (27: == CONFIG-0020-D F0: = -)  ; 27..EF ==
CONFIG-0020-D (10: == / 40: = -)              ; 10..3F ==

CONFIG-0021   (    =  CONFIG-0021-A)          ; 00..FF =
CONFIG-0021-A (10: =  CONFIG-0021-B F0: = -)  ; 10..EF =
CONFIG-0021-B (04: =  CONFIG-0021-C B0: = -)  ; 04..AF =
CONFIG-0021-C (17: == CONFIG-0021-D 46: = -)  ; 17..45 ==
CONFIG-0021-D (05: =  / 40: = -)              ; 05..3F =

CONFIG-0022   (    =  CONFIG-0022-A)          ; 00..FF =
CONFIG-0022-A (10: =  CONFIG-0022-B F0: = -)  ; 10..EF =
CONFIG-0022-B (04: =  CONFIG-0022-C B0: = -)  ; 04..AF =
CONFIG-0022-C (17: == CONFIG-0022-D 46: = -)  ; 17..45 ==
CONFIG-0022-D (05: =  CONFIG-0022-E 40: = -)  ; 05..3F =
CONFIG-0022-E (05: == / 20: = -)              ; 05..1F ==
